name: ESLint
on:
    push:
        branches:
            - '*'
            - '!docs'
            - '!develop'
            - '!master'
            - '!gh-pages'
    pull_request:
        branches:
            - '*'
            - '!docs'
            - '!develop'
            - '!master'
            - '!gh-pages'
jobs:
    test:
        name: ESLint (Node v16)
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Install Node v16
              uses: actions/setup-node@v1
              with:
                  node-version: 18

            - name: Install dependencies
              run: yarn install --immutable

            - name: Run ESLint
              run: yarn lint

            - name: Run TSC
              run: yarn build:check
